rsa: 
   public-key: classpath:certs/pub.pem
spring:
      jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
      application:
                 name: etudiant-service
      config:
            import: optional:configserver:http://localhost:8888
