spring:
       cloud: 
             config: 
                   enabled: false
                   import-check: 
                                enabled: false
             discovery: 
                      enabled: false
       datasource:
                 url: jdbc:h2:mem:etudiantInscriptionFiliere-service
                 driverClassName: org.h2.Driver
                 username: AF
                 password: 
       jpa:
           database-platform: org.hibernate.dialect.H2Dialect    
       h2: 
         console: 
                enabled: true           
springdoc: 
         api-docs: 
                 enabled: true    
         swagger-ui: 
                   enabled: true 
server: 
      port: 1010



