spring:
       cloud: 
             config: 
                   enabled: false
                   import-check: 
                                enabled: false
             discovery: 
                      enabled: false
       datasource:
         url: jdbc:mysql://localhost/student-service?createDatabaseIfNotExist=true&serverTimezone=UTC
         username: root
         password:
         driver-class-name: com.mysql.cj.jdbc.Driver
       jpa:
         hibernate:
           ddl-auto: update
         show-sql: true

springdoc: 
         api-docs: 
                 enabled: true    
         swagger-ui: 
                   enabled: true 
server: 
      port: 1010   
                                           