eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
   application:
       name: ETUDAINTINSCRIPTIONFILIERE-SERVICE
   datasource:
         url: jdbc:mysql://localhost/student-service?createDatabaseIfNotExist=true&serverTimezone=UTC
         username: root
         password:
         driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
         hibernate:
           ddl-auto: update
         show-sql: true

springdoc: 
         api-docs: 
                 enabled: true    
         swagger-ui: 
                   enabled: true 
server: 
      port: 1010   
                                           