eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: note
          uri: http://localhost:8089
          predicates:
            - Path=/api/note-service/**
        - id: enseignant
          uri: http://localhost:8086
          predicates:
            - Path=/api/enseignant-service/**
      default-filters: 
               - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
               allowedOrigins: "http://localhost:4200"
               allowedHeaders: "*"
               allowedMethods: "*"
       
