eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: note
          uri: http://localhost:8089
          predicates:
            - Path=/api/modules/**
        - id: note
          uri: http://localhost:8089
          predicates:
            - Path=/api/notes/**
        - id: note
          uri: http://localhost:8089
          predicates:
            - Path=/api/examens/**