spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters: 
               - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
               allowedOrigins: "http://localhost:4200"
               allowedHeaders: "*"
               allowedMethods: "*"

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true


eureka:
  client:
    service-url:
      defaultZone=http://user: pass@localhost:8761/eureka
    register-with-eureka: false


server:
  port: 8222
