eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: note
  datasource:
    url: jdbc:mysql://localhost/note-service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8089
  servlet:
    context-path: /api/note-service
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include : health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      notec:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState : 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
