eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: note
  datasource:
    url: jdbc:h2:mem:note_service_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



