eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: NOTE-SERVICE
  datasource:
    url: jdbc:h2:mem:note_service_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8089
  servlet:
    context-path: /api

h2:
  console:
    enabled: true


application:
  config:
    modules-url: http://localhost:8222/api/modules

management:
  tracing:
    sampling:
      probability: 1.0
