eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
      application:
         name: security-service
      jpa:
         hibernate:
                  ddl-auto: update
         show-sql: true
      datasource: 
                 url: jdbc:mysql://localhost/security-service?createDatabaseIfNotExist=true
                 username: root
                 password: 
                 driverClassName: com.mysql.cj.jdbc.Driver
server:
      port: 9800
serverTimezone: UTC